In [2]:
import numpy as np
data = np.load('../data/NAN_Remove_train.npy')

In [3]:
isinstance(data[:,1], str)

False

In [4]:
print data
temp = data[1,1]
print temp[0:4]
print temp[5:7]
print temp[8:10]

[[1 '2011-08-20' 43 ..., 52 4 5850000]
 [2 '2011-08-23' 34 ..., 66 14 6000000]
 [3 '2011-08-27' 43 ..., 67 10 5700000]
 ..., 
 [30471 '2015-06-30' 45 ..., 11 1 6970959]
 [30472 '2015-06-30' 64 ..., 65 7 13500000]
 [30473 '2015-06-30' 43 ..., 54 10 5600000]]
2011
08
23


In [5]:
#Change date format
year = np.zeros((data.shape[0],1))
month = np.zeros((data.shape[0],1))
day = np.zeros((data.shape[0],1))
dt = np.zeros((data.shape[0],1))
for i in range(data.shape[0]):
    temp = data[i,1]
    year[i] = temp[0:4]
    month[i] = temp[5:7]
    day[i] = temp[8:10]
print year.shape 
idx = data[:,0]
idx = np.reshape(idx,(idx.shape[0],1))
RestData = data[:,2:data.shape[1]]
dt = np.concatenate((idx,year,month,day,RestData),1)
print dt.shape,idx.shape

(30471, 1)
(30471, 243) (30471, 1)


In [6]:
#Encode column 5
j = 0
for i in range(dt.shape[0]):
    if dt[i,5] == 'Investment':
        dt[i,5] = 1
        j +=1
    elif dt[i,5] == 'OwnerOccupier':
        dt[i,5] = 2
        j +=1
print j



30471


In [9]:
#Encode Column 6
from sklearn import preprocessing
le6 = preprocessing.LabelEncoder()
le6.fit(dt[:,6])
dt[:,6] = le6.transform(dt[:,6])
print dt[0:10,6]

[9 70 129 65 6 73 122 9 44 50]


In [18]:
#Encode Column20
le20 = preprocessing.LabelEncoder()
le20.fit(dt[:,20])
dt[:,20] = le20.transform(dt[:,20])
print dt[0:10,20]

[0 1 0 0 0 0 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]


In [ ]:
#Encode Column24
le24 = preprocessing.LabelEncoder()
le24.fit(dt[:,24])
dt[:,24] = le24.transform(dt[:,24])
print dt[0:10,24]


In [ ]:
#Encode Column25
le25 = preprocessing.LabelEncoder()
le25.fit(dt[:,25])
dt[:,25] = le25.transform(dt[:,25])
print dt[0:10,25]

In [23]:
#Encode Column26
le26 = preprocessing.LabelEncoder()
le26.fit(dt[:,26])
dt[:,26] = le26.transform(dt[:,26])
print dt[0:10,26]

[0 0 0 0 0 0 0 0 0 0]


In [31]:
#Encode Column27 28 29 30 31 76 84 88
le27 = preprocessing.LabelEncoder()
le27.fit(dt[:,27])
dt[:,27] = le27.transform(dt[:,27])
dt[:,28] = le25.transform(dt[:,28])
dt[:,29] = le25.transform(dt[:,29])
dt[:,30] = le25.transform(dt[:,30])
dt[:,31] = le25.transform(dt[:,31])
dt[:,76] = le25.transform(dt[:,76])
dt[:,84] = le25.transform(dt[:,84])
dt[:,88] = le25.transform(dt[:,88])
print dt[0:10,27]
print dt[0:10,28]
print dt[0:10,29]
print dt[0:10,30]
print dt[0:10,31]
print dt[0:10,76]
print dt[0:10,84]
print dt[0:10,88]

[0 0 1 0 1 1 0 0 0 1]
[0 0 0 0 1 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 1 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0]


In [34]:
#Encode Column26
le122 = preprocessing.LabelEncoder()
le122.fit(dt[:,122])
dt[:,122] = le122.transform(dt[:,122])
print dt[0:10,122]

[1 0 3 1 0 3 3 1 3 4]


In [37]:
for i in range(dt.shape[0]):
    for j in range(dt.shape[1]):
        var = dt[i,j]
        if (isinstance(var, str)):
            print "str", (i,j)

In [27]:
print dt[0:10,28]
print dt[0:10,29]
print dt[0:10,30]
print dt[0:10,31]
print dt[0:10,76]
print dt[0:10,84]
print dt[0:10,88]
print dt[0:10,122]


['no' 'no' 'no' 'no' 'yes' 'no' 'no' 'no' 'no' 'no']
['no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no']
['no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no']
['no' 'no' 'no' 'no' 'no' 'no' 'yes' 'no' 'no' 'no']
['no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no']
['no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no']
['no' 'no' 'no' 'no' 'yes' 'no' 'no' 'no' 'no' 'no']
['good' 'excellent' 'poor' 'good' 'excellent' 'poor' 'poor' 'good' 'poor'
 'satisfactory']


In [39]:
np.save('../data/PreProcessData.npy',dt)