In [1]:
import numpy as np
data = np.load('../data/NAN_Remove_test.npy')

In [2]:
isinstance(data[:,1], str)

False

In [3]:
print data
temp = data[1,1]
print temp[0:4]
print temp[5:7]
print temp[8:10]

[[30474 '2015-07-01' 39.0 ..., 0 14 1]
 [30475 '2015-07-01' 79.2 ..., 1 12 1]
 [30476 '2015-07-01' 40.5 ..., 10 71 11]
 ..., 
 [38133 '2016-05-30' 41.08 ..., 105 203 13]
 [38134 '2016-05-30' 34.8 ..., 2 43 10]
 [38135 '2016-05-30' 63.0 ..., 4 42 11]]
2015
07
01


In [4]:
#Change date format
year = np.zeros((data.shape[0],1))
month = np.zeros((data.shape[0],1))
day = np.zeros((data.shape[0],1))
dt = np.zeros((data.shape[0],1))
for i in range(data.shape[0]):
    temp = data[i,1]
    year[i] = temp[0:4]
    month[i] = temp[5:7]
    day[i] = temp[8:10]
print year.shape 
idx = data[:,0]
idx = np.reshape(idx,(idx.shape[0],1))
RestData = data[:,2:data.shape[1]]
dt = np.concatenate((idx,year,month,day,RestData),1)
print dt.shape,idx.shape

(7662, 1)
(7662, 245) (7662, 1)


In [5]:
#Encode column 5
j = 0
for i in range(dt.shape[0]):
    if dt[i,5] == 'Investment':
        dt[i,5] = 1
        j +=1
    elif dt[i,5] == 'OwnerOccupier':
        dt[i,5] = 2
        j +=1
print j



0


In [9]:
#Encode Column 6
from sklearn import preprocessing
le6 = preprocessing.LabelEncoder()
le6.fit(dt[:,6])
dt[:,6] = le6.transform(dt[:,6])
print dt[0:10,6]

[9 70 129 65 6 73 122 9 44 50]


In [18]:
#Encode Column20
le20 = preprocessing.LabelEncoder()
le20.fit(dt[:,20])
dt[:,20] = le20.transform(dt[:,20])
print dt[0:10,20]

[0 1 0 0 0 0 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]


In [ ]:
#Encode Column24
le24 = preprocessing.LabelEncoder()
le24.fit(dt[:,24])
dt[:,24] = le24.transform(dt[:,24])
print dt[0:10,24]


In [ ]:
#Encode Column25
le25 = preprocessing.LabelEncoder()
le25.fit(dt[:,25])
dt[:,25] = le25.transform(dt[:,25])
print dt[0:10,25]

In [23]:
#Encode Column26
le26 = preprocessing.LabelEncoder()
le26.fit(dt[:,26])
dt[:,26] = le26.transform(dt[:,26])
print dt[0:10,26]

[0 0 0 0 0 0 0 0 0 0]


In [31]:
#Encode Column27 28 29 30 31 76 84 88
le27 = preprocessing.LabelEncoder()
le27.fit(dt[:,27])
dt[:,27] = le27.transform(dt[:,27])
dt[:,28] = le25.transform(dt[:,28])
dt[:,29] = le25.transform(dt[:,29])
dt[:,30] = le25.transform(dt[:,30])
dt[:,31] = le25.transform(dt[:,31])
dt[:,76] = le25.transform(dt[:,76])
dt[:,84] = le25.transform(dt[:,84])
dt[:,88] = le25.transform(dt[:,88])
print dt[0:10,27]
print dt[0:10,28]
print dt[0:10,29]
print dt[0:10,30]
print dt[0:10,31]
print dt[0:10,76]
print dt[0:10,84]
print dt[0:10,88]

[0 0 1 0 1 1 0 0 0 1]
[0 0 0 0 1 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 1 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0]


In [34]:
#Encode Column26
le122 = preprocessing.LabelEncoder()
le122.fit(dt[:,122])
dt[:,122] = le122.transform(dt[:,122])
print dt[0:10,122]

[1 0 3 1 0 3 3 1 3 4]


In [6]:
for i in range(1):
    for j in range(dt.shape[1]):
        var = dt[i,j]
        if (isinstance(var, str)):
            print "str", (i,j)

str (0, 10)
str (0, 24)
str (0, 28)
str (0, 29)
str (0, 30)
str (0, 31)
str (0, 32)
str (0, 33)
str (0, 34)
str (0, 35)
str (0, 80)
str (0, 88)
str (0, 92)
str (0, 126)


In [7]:
print dt[0:10,10]
print dt[0:10,29]
print dt[0:10,30]
print dt[0:10,31]
print dt[0:10,76]
print dt[0:10,84]
print dt[0:10,88]
print dt[0:10,122]


['Juzhnoe Butovo' 'Poselenie Vnukovskoe' 'Perovo' 'Poselenie Voskresenskoe'
 'Poselenie Vnukovskoe' 'Filevskij Park' 'Solncevo' 'Poselenie Sosenskoe'
 'Vnukovo' 'Poselenie Vnukovskoe']
['no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no']
['no' 'no' 'yes' 'no' 'no' 'no' 'no' 'no' 'no' 'no']
['no' 'no' 'yes' 'no' 'no' 'yes' 'no' 'no' 'no' 'no']
[39 24 59 39 24 14 34 105 19 118]
[24.07970721 20.86442659 8.67108556 26.22604543 21.03856121 5.574358192
 16.10136105 19.6032973 23.58910384 23.11817841]
['no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no']
[19.95341267 13.00610746 2.9838746460000003 18.12121993 13.45959327
 2.7957909410000004 8.634607397 10.42324316 15.3522671 20.21555842]


In [39]:
np.save('../data/PreProcessData.npy',dt)